tasks:
  - init: |
      docker run --rm -d -p 6379:6379 --name redis redis
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
